In [1]:
from importlib_metadata.compat.py39 import normalized_name
!pip install numpy


In [6]:
import numpy as np

## create a numpy
## create a 1d array

arr1 = np.array([1,2,3,4,5])
print((arr1))
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape((1,5)) ## 1 row and 5 element



array([[1, 2, 3, 4, 5]])

In [8]:
## another way for decleration

arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [10]:
## 2d array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [14]:
np.arange(0,10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [17]:
np.ones((3,4)) ## 3 row and 4 colum with all is one filled

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
## Identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
## Attribute of numpy
arr = np.array([[1,2,3],[4,5,6]])

print("Array : \n",arr)
print("shape of array : ",arr.shape)
print("Number of dimensions : ",arr.ndim)
print("size(number of element) : ",arr.size)
print("Data type : ",arr.dtype)
print("Item size : ",arr.itemsize)

Array : 
 [[1 2 3]
 [4 5 6]]
shape of array :  (2, 3)
Number of dimensions :  2
size(number of element) :  6
Data type :  int64
Item size :  8


In [25]:
## Numpy vectorized oparation (all the return type is array)

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])


print("Addition : ",arr1+arr2)
print("Subtraction : ",arr1-arr2)
print("Multiplication : ",arr1*arr2)
print("Division : ",arr1/arr2)

Addition :  [11 22 33 44 55]
Subtraction :  [ -9 -18 -27 -36 -45]
Multiplication :  [ 10  40  90 160 250]
Division :  [0.1 0.1 0.1 0.1 0.1]


In [27]:
## univarsal Funtion

arr = np.array([2,3,4,5,6])

## squre root
print(np.sqrt(arr))

## exponensisal

print(np.exp(arr))

## sine

print(np.sin(arr))

## natural log

print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [28]:
## Array slicing and indexing

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array : \n",arr)

Array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
arr[0][1]

np.int64(2)

In [35]:
arr[1:,2:]

array([[6],
       [9]])

In [36]:
print(arr[0][0])
print(arr[0:2])

1
[[1 2 3]
 [4 5 6]]


In [38]:
## statistical concept -- normalization
## to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

## calculate mean of standard deviation

mean = np.mean(data)
stv_dev=np.std(data)

## Normalized the data

normalized_data = (data-mean)/stv_dev
print("Normalized data : ",normalized_data)

Normalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
